### ISSUE TITLE
Can not download BFD_1.3M.hdf5

### ISSUE THREAD

**Issue by qiyifei1** [psipred/DMPfold2#1]
I got the following error when trying to download BFD_1.3M.hdf5
at https://figshare.com/articles/dataset/Protein_structures_predicted_using_DMPfold2/14979990?file=28893897
{"message": "Storage exception: Unexpected scenario inst_id=549 state=ic_failure", "code": "StorageException”}

It seems the file is incompletely uploaded.

**Comment by shaunmk** [comment]
Thanks for bringing this to our attention. I have re-uploaded the file and verified that it downloads correctly. Please ensure that you are now downloading from version 3 of the dataset using this link: https://doi.org/10.5522/04/14979990.v3 (the link in the README also works).

The output from `md5sum` should be:
`67992d6b7d04754515a4565edc9c6d67  BFD_1.3M.hdf5`

**Comment by qiyifei1** [comment]
It's good now. Thank you.
