### ISSUE TITLE
Sequence alignment in `.aln` format

### ISSUE THREAD

**Issue by knuser** [psipred/DMPfold2#2]
Is there any specification for `.aln` format available? Or are there any tools converting from `.a3m` format to `.aln`?

I did google for `.aln` specification, but nothing found. I had tried also using converter from https://github.com/soedinglab/hh-suite/blob/master/scripts/reformat.pl, but non of the output had matched provided example (https://github.com/psipred/DMPfold2/tree/master/dmpfold/example/PF10963.aln).

I did check also online version of `HHblits`, but also did not found way to download results in your format. Here is my job:
https://toolkit.tuebingen.mpg.de/jobs/8863800

Sequence I'm looking alignment for is `MDVVSLDKPFMYFEEIDNELDYEPESANEVAKKLPYQGQLKLLLGELFFLSKLQRHGILDGATVVYIGSAPGTHIRYLRDHFYNLGVIIKWMLIDGRHHDPILNGLRDVTLVTRFVDEEYLRSIKKQLHPSKIILISDVASAAGGNEPSTADLLSNYALQNVMISILNPVASSLKWRCPFPDQWIKDFYIPHGNKMLQPFAPSYSAEMRLLSIYTGENMRLTRVTKSDAVNYEKKMYYLNKIVRNKVVVNFDYPNQEYDYFHMYFMLRTVYCNKTFPTTKAKVLFLQQSIFRFLNIP`

My a3m file: [rcsb_pdb_2GAF_part.a3m.txt](https://github.com/psipred/DMPfold2/files/8022471/rcsb_pdb_2GAF_part.a3m.txt)

**Comment by shaunmk** [comment]
Hi, 

You can convert an alignment in a3m format to `.aln` format using a couple of shell commands; we use this:

```$ grep -v '^>' file.a3m | sed -e 's/[a-z]//g' > file.aln```

In short, you only have to remove the lines beginning with '>' and delete lowercase characters from the a3m file. In both a3m and aln alignments, the query sequence should be the first sequence.

HTH

**Comment by knuser** [comment]
Thank you, works excellent!

My `.a3m` examples got `#` in first line, so I made small modification to have more universal command:

`$ sed -e 's/[a-z]//g' file.a3m | grep '^[A-Z\-]' > file.aln`
