### ISSUE TITLE
cannot reshape array of size ... into shape (..., ...)

### ISSUE THREAD

**Issue by esmeraldalegarda** [psipred/DMPfold2#5]
Hi, I was trying to run DMPfold2, but the next error appeared:

Traceback (most recent call last):
  File "./dmpfold", line 5, in <module>
    run_dmpfold()
  File "/home/esgarle/.local/lib/python3.8/site-packages/dmpfold/predict.py", line 175, in run_dmpfold
    coords, confs, alnmat = aln_to_coords(args.input_file, device=args.device,
  File "/home/esgarle/.local/lib/python3.8/site-packages/dmpfold/predict.py", line 121, in aln_to_coords
    alnmat = (np.frombuffer(''.join(aln).translate(aa_trans).encode('latin-1'), dtype=np.uint8) - ord('A')).reshape(nseqs,length)
ValueError: cannot reshape array of size 1977853 into shape (10740,41)

I am not sure if this error is related to the size of the input file, with aln format. It contains around 1500 sequences.

**Comment by andymlau** [comment]
Hi, it looks like your input file might not be in the `.aln` format, as I could reproduce the error by giving DMPfold2 an `.a3m` file. See here for more information: https://github.com/psipred/DMPfold2/issues/2

**Comment by esmeraldalegarda** [comment]
Thank you. I got confused with the .aln format of ClustalW. Also important to remark that there should not be any gap in the first sequence. After all, it worked great!
