### ISSUE TITLE
Recommendation to build side-chain conformations after dmpfold?

### ISSUE THREAD

**Issue by johnnytam100** [psipred/DMPfold2#6]
Hi, dmpfold is really fast! Thanks!
I would like to know if dmpfold has been further evaluated by building side-chain conformations to the output backbone structure?
If yes, which package do you recommend to build side-chain conformations after dmpfold?

**Comment by andymlau** [comment]
Hi, thanks for the interest! We haven't assessed our models in combination with added sidechains, but programs such as SCRWL4 will be able to add them for you.
