### ISSUE TITLE
Recommendations for handling ambiguous amino acid characters (X and N)?

### ISSUE THREAD

**Issue by laelbarlow** [psipred/DMPfold2#7]
I noticed that input alignments with characters "X" and "N" cause a KeyError at line 202 of the predict.py script. Obviously DMPfold2 is only set up to handle the basic 20 amino acid alphabet. 

Do you have any recommendations for how to generate predictions from such alignments without simply removing columns with ambiguous characters?

**Comment by andymlau** [comment]
Hi, if the characters aren't in the target sequence, you could replace them with a gap character '-'. If they are, then as you suggested, the column would need to be removed. If there aren't too many non-standard residues in the target sequence and they're ones such as B, Z or J, then you could also try replacing them with one of their standard residues (swapping B to N/D and Z to Q/E, for example).
